# Generated by Django 4.2 on 2023-05-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
    ]
