# Generated by Django 4.2 on 2023-04-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poule', to='FinalWhistle.poule'),
            preserve_default=False,
        ),
    ]
