# Generated by Django 4.2 on 2023-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0002_game_tab_away_game_tab_home_alter_team_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='score_filled',
            field=models.IntegerField(default=0),
        ),
    ]
