# Generated by Django 4.2 on 2023-04-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0002_game_poule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='poule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='FinalWhistle.poule'),
        ),
    ]
