# Generated by Django 4.2 on 2023-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0005_tournament_date_end_tournament_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
