# Generated by Django 4.2 on 2023-04-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0005_tournament_end_date_tournament_start_date'),
        ('FinalWhistle', '0006_remove_game_score_game_away_score_game_home_score'),
    ]

    operations = [
    ]
