# Generated by Django 4.2 on 2023-04-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0007_merge_20230421_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='nPoule',
        ),
    ]
