# Generated by Django 4.2 on 2023-05-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0008_remove_game_npoule_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_quantity', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalWhistle.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FinalWhistle.round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='round',
            field=models.ManyToManyField(to='FinalWhistle.round'),
        ),
    ]
