# Generated by Django 4.2 on 2023-05-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0009_round_game_round_team_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalWhistle.round'),
        ),
        migrations.AlterField(
            model_name='team',
            name='round',
            field=models.ManyToManyField(null=True, to='FinalWhistle.round'),
        ),
    ]
