# Generated by Django 4.2 on 2023-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0010_alter_game_round_alter_team_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
