# Generated by Django 4.2 on 2023-05-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0011_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='poule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalWhistle.poule'),
        ),
    ]
