# Generated by Django 4.2 on 2023-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0012_alter_game_location_alter_game_poule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(null=True),
        ),
    ]
