# Generated by Django 4.2 on 2023-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0013_alter_game_away_score_alter_game_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_filled',
            field=models.IntegerField(null=True),
        ),
    ]
