# Generated by Django 4.2 on 2023-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalWhistle', '0014_round_round_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_filled',
            field=models.IntegerField(default=0),
        ),
    ]
